//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pgmpm.Visualization.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutomaticallyAlignNodes {
            get {
                return ((bool)(this["AutomaticallyAlignNodes"]));
            }
            set {
                this["AutomaticallyAlignNodes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int TransitionHeight {
            get {
                return ((int)(this["TransitionHeight"]));
            }
            set {
                this["TransitionHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int TransitionWidth {
            get {
                return ((int)(this["TransitionWidth"]));
            }
            set {
                this["TransitionWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int PlaceRadius {
            get {
                return ((int)(this["PlaceRadius"]));
            }
            set {
                this["PlaceRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int PositionCorrection {
            get {
                return ((int)(this["PositionCorrection"]));
            }
            set {
                this["PositionCorrection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public int ColumnWidth {
            get {
                return ((int)(this["ColumnWidth"]));
            }
            set {
                this["ColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public int RowHeight {
            get {
                return ((int)(this["RowHeight"]));
            }
            set {
                this["RowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int DefaultStrokeThickness {
            get {
                return ((int)(this["DefaultStrokeThickness"]));
            }
            set {
                this["DefaultStrokeThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFD3D3D3")]
        public global::System.Windows.Media.SolidColorBrush DefaultBackgroundColor {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["DefaultBackgroundColor"]));
            }
            set {
                this["DefaultBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public global::System.Windows.Media.SolidColorBrush DefaultBorderColor {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["DefaultBorderColor"]));
            }
            set {
                this["DefaultBorderColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public global::System.Windows.Media.SolidColorBrush DefaultStrokeColor {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["DefaultStrokeColor"]));
            }
            set {
                this["DefaultStrokeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SizeAll")]
        public global::System.Windows.Input.Cursor DefaultMoveCursor {
            get {
                return ((global::System.Windows.Input.Cursor)(this["DefaultMoveCursor"]));
            }
            set {
                this["DefaultMoveCursor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF0000")]
        public global::System.Windows.Media.SolidColorBrush DeletedNodeColor {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["DeletedNodeColor"]));
            }
            set {
                this["DeletedNodeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFF00")]
        public global::System.Windows.Media.SolidColorBrush AddedNodeColor {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["AddedNodeColor"]));
            }
            set {
                this["AddedNodeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFA500")]
        public global::System.Windows.Media.SolidColorBrush ChangedNodeColor {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["ChangedNodeColor"]));
            }
            set {
                this["ChangedNodeColor"] = value;
            }
        }
    }
}
